### ISSUE TITLE
tattoo shop

### ISSUE THREAD

**Issue by IRAN-HIGH** [ChickSH/raid_clothes#1]
hi dude nice work but tattoo shop not working

**Comment by ChickSH** [comment]
ill upload the new one, with tatto and hair shops


‫בתאריך יום ב׳, 10 באוג׳ 2020 ב-2:28 מאת ‪IRAN-HIGH-RP‬‏ <‪
notifications@github.com‬‏>:‬

**Comment by IRAN-HIGH** [comment]
when i go to  tattoo shop and press m  not happening any thnig  dont see ui  . and no blip for tattoo shop on map

**Comment by ChickSH** [comment]
currently uploading it, soon you will see it in github ;D .


‫בתאריך יום ב׳, 10 באוג׳ 2020 ב-3:21 מאת ‪IRAN-HIGH-RP‬‏ <‪
notifications@github.com‬‏>:‬

**Comment by IRAN-HIGH** [comment]
thx u dude
